### ISSUE TITLE
iOS4+ unsupported

### ISSUE THREAD

**Issue by ericwchui** [eklipse2k8/FilterKit#1]
Looks like this is no longer supported for iOS4+? There are methods like setBackgroundImage: forBarMetrics: which are iOS5+ only, and even after i commented out those lines and managed to build and run the app, the UIActivityIndicator keep spinning after I crop/scale the selected image. 

Same problem for both my iOS4.0 3GS and the iOS4.3 simulator.

**Comment by eklipse2k8** [comment]
Yeah, since Apple has set the minimum target to 4.3 now, we might as well jump to 5.0 as all devices that can run 4.3 can also run 5.0.
