### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by JoeFerrucci** [eklipse2k8/FilterKit#3]
Downloaded the.zip and ran the FilterDemoApp.xcodeproj and it complained of missing all the header files beginning with:
# import "GPUImageMonochromeFilter.h"

Screenshot attached. 

*Note: looks like the the directory which everything was unzipped to "FilterKit-master" contains a folder called "lib" with a folder called "GPUImage" inside, and that folder is EMPTY.  Should it contain something? Why is it empty? Help me out please. Thanks!

![Screen Shot 2013-01-02 at 2 41 06 AM](https://f.cloud.github.com/assets/2114494/38030/f22df264-54c8-11e2-856b-26d025a92089.png)

**Comment by AliSoftware** [comment]
This is because `GPUImage` was added as a GIT submodule by the author of this GIT repository.

You simply need to call `git submodule init` and then `git submodule update` to retrieve the submodules of the repository. See [here for more instructions and info](http://git-scm.com/book/en/Git-Tools-Submodules#Cloning-a-Project-with-Submodules).

Alternatively, you could have cloned this repository by using the `--recursive` flag when calling `git clone` ; this flag tell your GIT client to init and update submodules right after the cloning (and is strictly equivalent to the previously explained 2 `git submodule` commands)

**Comment by ozlembil** [comment]
hello,
i am totally new to xcode and i didn't understand this above instructions.any other way you can suggest? thanks in advanced

**Comment by JoeFerrucci** [comment]
ozlembil, he is suggesting that you clone the repository again using the `--recursive` flag. If you're not familiar with git just Google for a quick tutorial. If you are familiar with git but you are not familiar with the commands given by AliSoftware then you can just Google those specific commands to get the information you need. 

The idea behind a new clone is that you will receive updated submodules that were added to the repository after the fact.

**Comment by ozlembil** [comment]
thank you CoderJoes  ,i am checking tutorials.hopefully make more sense in the future

**Comment by nickthedude** [comment]
im getting linker errors even after cloning the sub modules. i also did a clean as well but it's still complaining about not having the gpuimage stuff. i also tried adding the lib manually to the demo app target with no luck.

**Comment by anitalanet** [comment]
I want to apply live filtering while capturing video how can perform that functionality in my ios app using filterkit and GUImage library

**Comment by anitalanet** [comment]
Missing  GPUImageMonochromeFilter.h...how to solve that issue.

**Comment by pulgaroja** [comment]
Hello I realize this issue has been closed for some time now, but I tried both git clone --recursive (in my Developer folder) and git submodule init (from within lib folder in the FilterKit) and am receiving the same error on both commands:

Cloning into 'lib/GPUImage'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:eklipse2k8/GPUImage.git' into submodule path 'lib/GPUImage' failed
